#! /bin/bash

# saving IPV6 address into a file
ip a | grep lo: -A 5 | grep global | cut -d " " -f 6 | cut -d "/" -f 1 > IPv6-Reflector

# executing nokia's twampy implementation
#python ./twampy/twampy.py responder $(cat IPv6-Reflector)

# executing scapy custom implementation
python3 ./twamp_test_reflector.py
